name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: sodium, openssl
          coverage: none
      - uses: ramsey/composer-install@v3
      - run: composer validate --strict
      - run: vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse --memory-limit=1G

